services:
  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: theatre_test
      MYSQL_USER: theatre
      MYSQL_PASSWORD: theatre
    ports:
      - "3321:3306"
    volumes:
      - database_test_data:/var/lib/mysql
  adminer:
    image: adminer
    ports:
      - "8082:8080"
volumes:
  database_test_data:
